### ISSUE TITLE
How to login after extension installation

### ISSUE THREAD

**Issue by IchHabRecht** [move-elevator/me_backend_security#1]
I installed the extension with Extension Manager and was logout out immediately. Now there seems to be no way to change my password as I cannot login anymore. Any advice how to be able to change my password for the first time after the extension was installed?

**Comment by phe95-me** [comment]
If the extension is installed and the timestamp of column tx_mebackendsecurity_lastpasswordchange is 0 (thats the default value), you should redirected to the password change login provider after login.
Please tell me more about your setup, so i can try to help you. Do you use extensions with other loginproviders like openid?

**Comment by IchHabRecht** [comment]
Hi @phe-move-elevator-de,

I'm using a fresh installation of TYPO3 8.7 without any additional extension. tx_mebackendsecurity_lastpasswordchange equals zero (by default) and after the backend user was processed and validated by TYPO3 core, your extension redirects in Classes/Service/BackendUserService.php:121 to index.php (with some magic parameters to show the notification message). Again I see the login screen and trying to login results in the same form over and over again. This equals exactly what the code in Classes/Service/BackendUserService.php says -> for all tx_mebackendsecurity_lastpasswordchange with a value of zero, there should be a redirect to the login form.

I don't see any way how to be able to login again.

**Comment by phe95-me** [comment]
Hy @IchHabRecht,
thank you. I have found the issue. If you not use SSL, the variable presetUsername is not assigned in \TYPO3\CMS\Backend\LoginProvider\UsernamePasswordLoginProvider and so the wrong template is loaded. Please try with SSL. We will release an update asap.

**Comment by phe95-me** [comment]
Version 1.1.2 is now available. This version should solve your login issue. :)
