### ISSUE TITLE
Remove calls to deprecated functions

### ISSUE THREAD

**Issue by saneinsane** [move-elevator/me_backend_security#10]
The TYPO3 extension scanner shows the following warnings:

Classes/Evaluation/PasswordEvaluator.php Call to method "addMessage()"
Classes/Hook/UserAuthHook.php Call to method "init()"
Classes/Hook/TableHook.php Call to method "addMessage()"

**Comment by Mainbird** [comment]
Hi @saneinsane ,
thank you for your feedback, but it looks like false positives here, so the scanner is complaining about methods that are deprecated in another class or scope. You can read more about it here: https://typo3.com/blog/typo3-v9s-new-extension-scanner-makes-planning-upgrades-easier#c5828

**Comment by Mainbird** [comment]
Hi @saneinsane,

do you agree with my feedback? If so, then I will close this issue. :)

**Comment by saneinsane** [comment]
@Mainbird I totally agree, sorry for not looking closer.
