### ISSUE TITLE
Does not work nice with core functionality password reset

### ISSUE THREAD

**Issue by zwenn** [move-elevator/me_backend_security#12]
Hi, I think me_backend_security shall work together with the password reset functionality from the core.

At the moment the password validation from this extension is not taken into account.
So that a beuser who has not logged in right now and resets his/her password, where able to enter a new unvalidated  password and after going back to the normal login form, first enter the new unvalidated password and then was prompted to enter another password.

I think that's not nice and not user-friendly.

Hope this would help to improve this extension even more.

**Comment by Mainbird** [comment]
Hi @zwenn 
thank you for your feedback and yes, I totally agree with you. The current behavior is not really user-friendly, I will check this as soon as possible.

**Comment by Mainbird** [comment]
Hi @zwenn we have released 2.0.7 today, which will work together with the password reset functionality. Special thanks to @vnc-kber. :)
