### ISSUE TITLE
Support TYPO3 v.11 and PHP 8

### ISSUE THREAD

**Issue by vnc-kber** [move-elevator/me_backend_security#14]
Hi, could you please add support for current TYPO3 and PHP versions?

**Comment by Mainbird** [comment]
Hi @vnc-kber, I am aware of the current lack of TYPO3 11 and PHP 8 support, but I am currently a little bit busy.  Nevertheless, I will try to make the required adjustments as soon as possible. :)

**Comment by Mainbird** [comment]
Hi @vnc-kber, I have added the support for TYPO3 11 and PHP 8 some days ago, but we have currently some trouble with syncing this mirror github repo with our main repo.

We will try to fix this issue as soon as possible and then I will release the new version (3.0.0) via packagist and TYPO3 TER.

**Comment by Mainbird** [comment]
Hi @vnc-kber, it is working now and I have released the new version on packagist and TYPO3 TER too. :)

- https://extensions.typo3.org/extension/me_backend_security
- https://packagist.org/packages/move-elevator/me-backend-security
