### ISSUE TITLE
Add option to disable the whole feature for a specific instance

### ISSUE THREAD

**Issue by nostadt** [move-elevator/me_backend_security#16]
First, thanks for developing this ext. We are using this to improve the security of our production instance. However, with this ext. installed it is impossible to create a BE user locally with a simple password. Like `foo:foo`.

So, it would be great to have a flag that allows developer to disable it as needed. Usually in local dev context.

I could not find an option to disable it.

Looking forward to hear from you.

Alexander

**Comment by Mainbird** [comment]
Hi Alexander,

thanks for your feedback. :)
I think you can also override the extension settings to achieve this. For example by a custom AdditionalConfiguration.php for your dev environment:

`
$GLOBALS['TYPO3_CONF_VARS']['EXTENSIONS']['me_backend_security']['minimumDigits'] = 0;
$GLOBALS['TYPO3_CONF_VARS']['EXTENSIONS']['me_backend_security']['minimumCapitalCharacters'] = 0;
$GLOBALS['TYPO3_CONF_VARS']['EXTENSIONS']['me_backend_security']['passwordLength'] = 1;
`

Would that be an option for you?

Kind regards,
Ronny

**Comment by nostadt** [comment]
Thanks, that sounds like a potential simple solution. I will check that.

**Comment by Mainbird** [comment]
Hi @nostadt did it work for you? I will close this issue now, feel free to open a new one if not. :)
