### ISSUE TITLE
MFA interfere with the force reset

### ISSUE THREAD

**Issue by thomas-lepage** [move-elevator/me_backend_security#18]
I found a small issue with the password reset.

We enforce the use of a MFA (TOTP for our case) for a certains type of BE users and it cause a loop when the password need to be changed.

I have a user that have a MFA setup and working. When the date come to force the change the password and it try to login, the MFA is asked, then the Password reset form is displayed. We fill all the input with valid values and when we submit it ask for the MFA again. We input the MFA info and we are back to the password reset form.

Thank you for the help!

Step to reproduce:
1. Create a BE User with a MFA setup
2. Set the last time password change to the past enough to force the password change
3. Try to login and change the password following the instruction

TYPO3 version: 11.5.24
Extension version: 3.0.1

**Comment by Mainbird** [comment]
Hi @thomas-lepage, thanks for your feedback. I am currently a little bit busy, but I will check this as soon as possible. :)

**Comment by Mainbird** [comment]
Hi @thomas-lepage, I have checked this today and I can confirm this issue with MFA enabled. I will try to fix this as soon as possible.

**Comment by thomas-lepage** [comment]
@Mainbird Thank you for the quick response!

**Comment by thomas-lepage** [comment]
@Mainbird Hi! I had some time to check and I found a solution. Can you check it out to see if it make sense?
There is a small description of what I did in the pull request.

https://github.com/move-elevator/me_backend_security/pull/19

**Comment by Mainbird** [comment]
Hi @thomas-lepage thanks a lot for your work and sorry for my late response. I am still a bit busy, but I will try to review your changes next week. :)

**Comment by Mainbird** [comment]
Hi @thomas-lepage sorry for my late response again, I am still a bit busy. 
I have checked your PR and it looks good to me, so I will release a new version of the extension with some other bugfixes as soon as possible. :)

**Comment by Mainbird** [comment]
Hi @thomas-lepage sorry for my late response, but I was quite busy. :(
The latest versions 3.0.2 and 3.0.3 are containing your MFA bugfix, thanks again for your work . :)

I will release these versions to TYPO3 TER today, too. Furthermore, me and my team mates will discuss if this extension is still useful for TYPO3 12+ soon or not. 

I will close the ticket now, feel free to create a new one if necessary.
