### ISSUE TITLE
SamePasswordValidator is bypassed in user settings

### ISSUE THREAD

**Issue by IchHabRecht** [move-elevator/me_backend_security#2]
If the user changes his/her password in the own user settings, the current password is not fetched and compared to the new password. If all other options are met, the same password is saved again and the tx_mebackendsecurity_lastpasswordchange timestamp is set to a current value.

**Comment by phe95-me** [comment]
Hello @IchHabRecht ,
thanks again for your report. This issue is fixed in [a5472f6](https://github.com/move-elevator/me_backend_security/commit/a5472f63d27715f6054f2c94eb86b9b1fcbd93b6) and will be available in next release.

**Comment by phe95-me** [comment]
Version 1.1.3 is now available. :)
