### ISSUE TITLE
Login as system maintainer not possible

### ISSUE THREAD

**Issue by Smove** [move-elevator/me_backend_security#4]
After installing the extension (2.0.1) I wanted to change the timestamp in the database to test it. After I have done this I get an error message after the login or after the password change form. 

> (1/1) #1294587486 TYPO3\CMS\Install\Exception
Session already started by session_start().<br />Make sure no installed extension is starting a session in its ext_localconf.php or ext_tables.php.

The stack shows a line with the comment "// If user is system maintainer, destroy its possibly valid install tool session."

![image](https://user-images.githubusercontent.com/3686891/62536374-24733280-b84e-11e9-8818-aa17d9b54ac7.png)

**Comment by Mainbird** [comment]
Hi @Smove I can confirm this for TYPO3 9, more details: https://github.com/move-elevator/me_backend_security/issues/6#issuecomment-741717255.

We will try to fix this asap.

**Comment by Mainbird** [comment]
I will close this issue because the newest release will not support TYPO3 9 anymore.
