### ISSUE TITLE
TYPO3 10 LTS compatible release

### ISSUE THREAD

**Issue by moe2k** [move-elevator/me_backend_security#5]
Are there any plans yet for a TYPO3 10 LTS compatible release or work in progess?
Are there particular points how I can help?

**Comment by danmoebius** [comment]
Hi, 
yes there are plans. We will start the work to release in a few weeks. 
Best regards

**Comment by moe2k** [comment]
That's great news! We'd like to do a little sponsoring as soon as the new version is out just for appreciation.
