### ISSUE TITLE
PHP version constraint <=7.4 allows 7.4.0 but not for example 7.4.10

### ISSUE THREAD

**Issue by NamelessCoder** [move-elevator/me_backend_security#7]
Due to the constraint, the extension is impossible to install on PHP 7.4 and it looks like the intention was to allow installing it on PHP up to and including all 7.4.x branches. Suggest switching to `^7.2` as constraint for PHP dep.

**Comment by Mainbird** [comment]
Hi @NamelessCoder, yes you are right that wasn't intended. We will fix this asap.

**Comment by Mainbird** [comment]
Hi @NamelessCoder we have released version 2.0.3 now, which contains the PHP version constraint fix.
